#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "friendica"
name = "Friendica"
description.en = "Decentralized Social Network"
description.fr = "Réseau social décentralisé"

version = "2026.01~ynh3"

maintainers = ["trendless"]

[upstream]
license = "AGPL-3.0-only"
website = "http://friendi.ca"
demo = "https://dir.friendica.social/servers"
admindoc = "https://github.com/friendica/friendica/wiki"
userdoc = "https://wiki.friendi.ca/"
code = "https://github.com/friendica/friendica"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true
sso = true

disk = "250M"
ram.build = "200M"
ram.runtime = "150M"

[install]
    [install.domain]
    type = "domain"

    [install.admin]
    type = "user"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = [ "de", "en", "es", "fr", "it", "pt" ]
    default = "en"

[resources]

    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/friendica/friendica/archive/c62cbe52f31f6e01a5293cc838f01ce0421a65b0.tar.gz"
        sha256 = "fa2021240e80509fd01f26d27fb173cc5bc80c5085d5123b606ede1668eda2d7"
        autoupdate.strategy = "latest_github_commit"

        [resources.sources.addons]
        url = "https://github.com/friendica/friendica-addons/archive/ecbdbe3ea988b1a57bc5f68f98f2f09a00e0c6da.tar.gz"
        sha256 = "dd9d9de53ae7ee65823e79b83c5d2c48aebfe4a71a8fbe592e997605b1d1f72c"
        autoupdate.upstream = "https://github.com/friendica/friendica-addons"
        autoupdate.strategy = "latest_github_commit"

        [resources.sources.bookface]
        url = "https://gitlab.com/randompenguin/bookface/-/archive/310b3b4c229fdffc660554df708590d361ffdffe/bookface-310b3b4c229fdffc660554df708590d361ffdffe.tar.gz"
        sha256 = "d11e56bb4254d204b8246d3d5902aef533f2a28bc8cc4748ce02d6e5550382d6"
        autoupdate.upstream = "https://gitlab.com/randompenguin/bookface"
        autoupdate.strategy = "latest_gitlab_commit"
        #autoupdate.asset = ".*\\.tar\\.gz"

[resources.system_user]

[resources.install_dir]
group = "www-data:r-x"

[resources.data_dir]
subdirs = ["storage"]
group = "www-data:rwx"

[resources.permissions]
main.url = "/"
main.show_tile = true
main.allowed = [ "visitors", "all_users" ]
main.protected = true

[resources.apt]
packages = ["mariadb-server", 
"php8.4-fpm", # DO NOT DROP THIS LINE, this fixes `phpapi` selection going south
"php8.4-imagick",
"php8.4-curl", 
"php8.4-mbstring", 
"php8.4-xml", 
"php8.4-zip", 
"php8.4-mysql", 
"php8.4-gd", 
"php8.4-gmp", 
"php8.4-intl", 
"php8.4-ldap", 
"php8.4-imap"]

[resources.database]
type = "mysql"
