#!/bin/bash

source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

(cd "$install_dir" && ynh_exec_as_app "php$php_version" bin/console.php maintenance 1)

trap '(cd $install_dir && ynh_exec_as_app php$php_version bin/console.php maintenance 0)' EXIT

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_backup "/etc/php/$php_version/fpm/pool.d/$app.conf"

ynh_backup "/etc/fail2ban/jail.d/$app.conf"
ynh_backup "/etc/fail2ban/filter.d/$app.conf"

ynh_backup "/etc/logrotate.d/$app"

ynh_backup "/var/log/$app"
ynh_backup "/etc/systemd/system/$app-daemon.service"

#=================================================
# BACKUP THE MYSQL DATABASE
#=================================================
ynh_print_info "Backing up the MySQL database..."

ynh_mysql_dump_db > db.sql

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
