#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# MODIFY URL IN FRIENDICA CONF
#=================================================

ynh_print_info "Updating the Friendica config..."

ynh_replace --match="'url' => 'https://.*'," --replace="'url' => 'https://$domain'," --file="$install_dir/config/local.config.php"
ynh_store_file_checksum "$install_dir/config/local.config.php"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
