#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

email=$(ynh_user_get_info --username=$admin --key=mail)
timezone=$(cat /etc/timezone)

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression --message="Storing installation settings..." --weight=1

ynh_app_setting_set --app=$app --key=email --value=$email

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=5

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"
ynh_setup_source --dest_dir="$install_dir/addon" --source_id="addons"

mkdir -p "$install_dir/view/smarty3"

chmod -R 775 "$install_dir/view/smarty3"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

ynh_add_config --template="local-sample.config.php" --destination="$final_path/config/local.config.php"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

# Create a dedicated PHP-FPM configy
ynh_add_fpm_config

# Create a dedicated nginx config
ynh_add_nginx_config

ynh_add_config --template="../conf/cron" --destination="/etc/cron.d/$app"
chown root: "/etc/cron.d/$app"
chmod 644 "/etc/cron.d/$app"

# Use logrotate to manage application logfile(s)
ynh_use_logrotate

# Create a dedicated Fail2Ban config
ynh_add_fail2ban_config --logpath="/var/log/nginx/${domain}-error.log" --failregex="^.*authenticate\: failed login attempt.*\"ip\"\:\"<HOST>\".*$"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding the LDAP Auth addon configuration file..." --weight=1

# LDAP addon config
ynh_add_config --template="../conf/addon.config.php" --destination="$install_dir/config/addon.config.php"

#=================================================
# INSTALL FRIENDICA
#=================================================
ynh_script_progression --message="Install Friendica..." --weight=1

pushd "$install_dir"
	# Import Composer dependencies
	ynh_exec_as "$app" php$phpversion bin/composer.phar install --no-dev --quiet

	# Install application
	ynh_exec_as "$app" php$phpversion bin/console.php autoinstall\
		--dbhost "localhost" --dbdata "$db_name" --dbuser "$db_user" --dbpass "$db_pwd"\
		--admin "$email" --tz "$timezone" --lang "$language" --url "https://$domain"

	# Enable LDAP Auth addon
	ynh_exec_as "$app" php$phpversion bin/console.php addon enable ldapauth

popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
