#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
# REMOVE SYSTEMD SERVICE 
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

# Remove the dedicated nginx config
ynh_remove_nginx_config

# Remove the dedicated PHP-FPM config
ynh_remove_fpm_config

# Remove the app-specific logrotate config
ynh_remove_logrotate

ynh_remove_fail2ban_config

ynh_secure_remove --file="/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
