#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================

if ynh_hide_warnings yunohost service status "$app-daemon" >/dev/null
then
	ynh_script_progression "Removing $app service integration..."
	yunohost service remove "$app-daemon"
fi

#=================================================
# REMOVE SYSTEMD SERVICE ETC
#=================================================

ynh_script_progression "Removing system configurations related to $app..."

ynh_config_remove_nginx

ynh_config_remove_phpfpm

ynh_config_remove_logrotate

ynh_config_remove_fail2ban

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
