#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================

ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app-daemon" --action="stop" --log_path="/var/log/$app/daemon.log"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --keep="config/local.config.php"
ynh_setup_source --dest_dir="$install_dir/addon" --source_id="addons"

ynh_safe_rm "$install_dir/view/smarty3/compiled"
mkdir "$install_dir/view/smarty3/compiled"
chmod -R 775 "$install_dir/view/smarty3"

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================

ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_phpfpm

ynh_config_add_logrotate

if [ -f "/etc/cron.d/$app" ]; then
  ynh_print_info "Removing the legacy cron..."
  ynh_safe_rm "/etc/cron.d/$app"
fi

ynh_config_add_systemd --service="$app-daemon"

yunohost service add "$app-daemon" --description="Friendica daemon" --log="/var/log/$app/daemon.log"

ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="^.*authenticate\: failed login attempt.*\"ip\"\:\"<HOST>\".*$"

#=================================================
# UPDATE A CONFIG FILE
#=================================================

ynh_script_progression "Updating configuration..."

if [ -f "$install_dir/config/local.config.php" ] && ! grep -q -e "'url' => 'https://$domain'," "$install_dir/config/local.config.php"; then
  ynh_print_info "Patching the Friendica config file: fix the domain setting..."
  ynh_replace --match="'url' => 'https://.*'," --replace="'url' => 'https://$domain'," --file="$install_dir/config/local.config.php"
  ynh_store_file_checksum "$install_dir/config/local.config.php"
fi

if [ -f "$install_dir/config/local.config.php" ] && ! grep -q -e "pidfile" "$install_dir/config/local.config.php"; then
  ynh_print_info "Patching the Friendica config file: add the PID file path for the daemon..."
  ynh_replace --match="'basepath' => '$install_dir'," --replace="'basepath' => '$install_dir',\n		'pidfile' => '$install_dir/daemon.pid'," --file="$install_dir/config/local.config.php"
  ynh_store_file_checksum "$install_dir/config/local.config.php"
fi

if [ -f "$install_dir/config/local.config.php" ] && ! grep -q -e "logfile" "$install_dir/config/local.config.php"; then
  ynh_print_info "Patching the Friendica config file: add the path for the Friendica logfile..."
  ynh_replace --match="'basepath' => '$install_dir'," --replace="'basepath' => '$install_dir',\n		'logfile' => '/var/log/friendica/friendica.log',\n		'loglevel' => 'notice'," --file="$install_dir/config/local.config.php"
  ynh_store_file_checksum "$install_dir/config/local.config.php"
fi

#=================================================
# STORE THE CONFIG FILE CHECKSUM
#=================================================

pushd "$install_dir"
  ynh_exec_as_app "php$php_version" bin/composer.phar install --no-dev --quiet
 	ynh_exec_as_app "php$php_version" bin/console.php dbstructure update
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================

ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app-daemon" --action="start" --log_path="/var/log/$app/daemon.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
